import { FretboardSystem } from '@moonwave99/fretboard.js';
import { FretboardMouseEventName, FretboardSystemOptions } from './FretboardJsExtraTypes';

export const FRETBOARD_MOUSE_EVENT_NAMES: FretboardMouseEventName[] = [
  'auxclick',
  'click',
  'contextmenu',
  'dblclick',
  'drag',
  'dragend',
  'dragenter',
  'dragleave',
  'dragover',
  'dragstart',
  'drop',
  'gotpointercapture',
  'lostpointercapture',
  'mousedown',
  'mouseenter',
  'mouseleave',
  'mousemove',
  'mouseout',
  'mouseover',
  'mouseup',
  'pointercancel',
  'pointerdown',
  'pointerenter',
  'pointerleave',
  'pointermove',
  'pointerout',
  'pointerover',
  'pointerup',
  'wheel',
];
